apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-docker-simple-deployment
  labels:
    app: go-docker-simple
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-docker-simple
  template:
    metadata:
      labels:
        app: go-docker-simple
    spec:
      containers:
      - name: go-docker-simple-container
        image: <go-docker-simple>:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
