apiVersion: v1
kind: Service
metadata:
  name: go-docker-simple-service
spec:
  selector:
    app: go-docker-simple
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
